export const AuthActionTypes = {
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  SET_APP_LANGUAGE: 'SET_APP_LANGUAGE',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_WELCOME_MESSAGE: 'UPDATE_WELCOME_MESSAGE',
};
